swagger:
  base-package: cn.bestsort.e_study.controller
spring:
  datasource:
    druid:
      url: '@jdbc.url@'
      username: '@jdbc.user@'
      password: '@jdbc.passwd@'
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        filter:
          stat:
            enabled: true
            db-type: mysql
            log-slow-sql: true
            slow-sql-millis: 2000
        filters:  stat,wall
        aop-patterns:
          - cn.bestsort.bbslite.service.*
          - cn.bestsort.bbslite.manager.*
logging:
  path: log